RANK_BEFORE = "rank_before"
RANK_BEFORE_S_PLUS = "rank_before_s_plus"
RANK_AFTER = "rank_after"
RANK_AFTER_S_PLUS = "rank_after_s_plus"
RANK_EXP_CHANGE = "rank_exp_change"
IS_RANK_UP = "is_rank_up"
CHALLENGE_WIN = "challenge_win"
CHALLENGE_LOSE = "challenge_lose"
