PRIMARY_ABILITY = "primary_ability"
ADDITIONAL_ABILITIES = "additional_abilities"
HEADGEAR = "headGear"
CLOTHING = "clothingGear"
SHOES = "shoesGear"
GEARS_KEYS = (HEADGEAR, CLOTHING, SHOES)

NAME = "name"
ME = "me"
PLAYER_NUMBER = "player_number"
SPLASHTAG = "splashtag"
WEAPON = "weapon"
INKED = "inked"
SPECIES = "species"
SCOREBOARD_POSITION = "scoreboard_position"
GEAR = "gear"
DISCONNECTED = "disconnected"

KILLS_OR_ASSISTS = "kills_or_assists"
ASSISTS = "assists"
KILLS = "kills"
DEATHS = "deaths"
SPECIALS = "specials"
SIGNALS = "signals"
TOP_500_CROWN = "top_500_crown"
