WEAPON = "weapon"
WEAPON_ID = (WEAPON, "id")
HEADGEAR = "headGear"
CLOTHING = "clothingGear"
SHOES = "shoesGear"
GEARS = [HEADGEAR, CLOTHING, SHOES]
NAME = "name"
IS_MYSELF = "isMyself"
PLAYER_NUMBER = "nameId"
NAMEPLATE = "nameplate"
BADGES = (NAMEPLATE, "badges")
BADGES_ID = (BADGES, "id", ":", "id")
SPLASHTAG = "byname"
INKED = "paint"
SPECIES = "species"
RESULT = "result"
DISCONNECTED = "disconnected"
KILL_OR_ASSIST = (RESULT, "kill")
ASSIST = (RESULT, "assist")
DEATH = (RESULT, "death")
SPECIAL = (RESULT, "special")
SIGNAL = (RESULT, "noroshiTry")
TOP_500_CROWN = "crown"
