WEAPON = ("weapon",)
WEAPON_ID = (WEAPON, "id")
WEAPON_NAME = (WEAPON, "name")
SUB_NAME = (WEAPON, "subWeapon", "name")
SPECIAL_NAME = (WEAPON, "specialWeapon", "name")
HEADGEAR = "headGear"
CLOTHING = "clothingGear"
SHOES = "shoesGear"
GEARS = [HEADGEAR, CLOTHING, SHOES]
NAME = "name"
ID = "id"
IS_MYSELF = "isMyself"
PLAYER_NUMBER = "nameId"
NAMEPLATE = "nameplate"
BADGES = (NAMEPLATE, "badges")
BADGES_ID = (BADGES, "id", ":", "id")
NAMEPLATE_TEXT_COLOR = (NAMEPLATE, "background", "textColor")
NAMEPLATE_BACKGROUND_ID = (NAMEPLATE, "background", "id")
SPLASHTAG = "byname"
INKED = "paint"
SPECIES = "species"
RESULT = "result"
DISCONNECTED = "disconnected"
KILL_OR_ASSIST = (RESULT, "kill")
ASSIST = (RESULT, "assist")
DEATH = (RESULT, "death")
SPECIAL = (RESULT, "special")
SIGNAL = (RESULT, "noroshiTry")
CROWN = "crown"
CROWN_TYPE = "festDragonCert"
