RESULT = "result"
PLAYERS = "players"
COLOR = "color"
PAINT_RATIO = (RESULT, "paintRatio")
SCORE = (RESULT, "score")
NOROSHI = (RESULT, "noroshi")
SPLATFEST_TEAM_NAME = "festTeamName"
SYNERGY_BONUS = "festUniformBonusRate"
SYNERGY_NAME = "festUniformName"
TRI_COLOR_ROLE = "tricolorRole"
ORDER = "order"
